apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-curl
  namespace: demo-light
  labels:
    app: debug-curl
    role: debug
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debug-curl
  template:
    metadata:
      labels:
        app: debug-curl
        role: debug
    spec:
      containers:
        - name: curl
          image: curlimages/curl:8.11.1
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - sleep infinity
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
