apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-nginx
  namespace: demo-light
  labels:
    app: frontend-nginx
    role: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-nginx
  template:
    metadata:
      labels:
        app: frontend-nginx
        role: frontend
    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 20m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-nginx
  namespace: demo-light
  labels:
    app: frontend-nginx
spec:
  type: ClusterIP
  selector:
    app: frontend-nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
